// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/a-h/pregel"
)

type Connection struct {
	Edges    []Edge   `json:"edges"`
	PageInfo PageInfo `json:"pageInfo"`
}

type Edge struct {
	Cursor string       `json:"cursor"`
	Node   *pregel.Node `json:"node"`
}

type NewEdge struct {
	Parent string `json:"parent"`
	Child  string `json:"child"`
}

type NewNode struct {
	ID       string   `json:"id"`
	Parents  []string `json:"parents"`
	Children []string `json:"children"`
}

type PageInfo struct {
	EndCursor       *string `json:"endCursor"`
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
}
