AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  pregelStoreLocal: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
        - 
          AttributeName: "rng"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
        - 
          AttributeName: "rng"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "pregelStoreLocal"
